### ISSUE TITLE
Rules around prediction.csv

### ISSUE THREAD

**Issue by shikhar-srivastava** [Rochester-Biomedical-DS/Hackathon-Summer-2024#1]
> Predictions on test data set are submitted by pushing to github. A repository with the name Hackathon-Summer-2024, owned by the team captain, **will be queried for a file named prediction/prediction.csv**. If the team captain forks this repository and writes predictions there everything should work (as long as the predictions are formatted correctly).

Please clarify the competition rules around below:
- What prevents competing teams from accessing this **prediction/prediction.csv**? 
- In which case, how is the original leader/owner of the prediction.csv determined?

Thanks!

**Comment by amandalarracuente** [comment]
Thanks for your questions. All captains must submit their own predictions. Any use of predictions from other teams is disqualifying. There are some measures we use to monitor potential problems during the competition. At the end of the competition, winning teams must submit the code used to generate their predictions to organizers to claim prizes.

**Comment by shikhar-srivastava** [comment]
Thank you @amandalarracuente!

That's helpful to know.
