### ISSUE TITLE
META dataset

### ISSUE THREAD

**Issue by aqjshi** [Rochester-Biomedical-DS/Hackathon-Summer-2024#2]
Hi, regarding the Meta dataset, 
nCount_RNA	nCount_ATAC	CellType
AAACCAACACAATGCC-1	5849	16550	CD14 Mono
I just need you to confirm that despite the omitting of the sequence, nCount_RNA	nCount_ATAC are the correct order right. Sorry for any inconvenience.

**Comment by hbliu** [comment]
Hi, regarding the Meta dataset,
nCount_RNA and nCount_ATAC are in the correct order.

Best,
Hongbo
