### ISSUE TITLE
Inquiry about order of cells

### ISSUE THREAD

**Issue by Jadehhhh** [Rochester-Biomedical-DS/Hackathon-Summer-2024#6]
Hi, I'm wondering if the order of cells in Meta.txt is the same as the order of the columns in RNA and ATAC? Thank you!

**Comment by hbliu** [comment]
Hi,
The answer is YES. You may check the data using the code:
https://github.com/Rochester-Biomedical-DS/Hackathon-Summer-2024/blob/main/data/Code.to.Check.Data.sh

Enjoy your Hackathon Summer 2024.

Best,
Hongbo
